// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'model.dart';

/// A mixin for [CalculatorService]. Don't forget to call [initState] in the constructor.
mixin CalculatorServiceModel {
  @protected
  @pragma('vm:prefer-inline')
  @pragma('dart2js:tryInline')
  CalculatorService get $ => this as CalculatorService;

  @protected
  EffectFnInfo? $effectFnInfo;
  Set<void Function()> $untrackedFns = const {};

  // -------------------- States --------------------------
  final counterState = ValueNotifier<int>(0);

  // -------------------- Computed ------------------------
  late final ValueNotifier<int> doubleCounterState = () {
    final state = ValueNotifier<int>($.doubleCounter);
    counterState.addListener($doubleCounterDepsChanged);
    return state;
  }();

  void $doubleCounterDepsChanged() {
    doubleCounterState.value = $.doubleCounter;
  }

  bool $initCalled = false;

  @mustCallSuper
  void initState() {
    if ($initCalled) return;
    $initCalled = true;

    final $ = this.$;

    counterState.value = $.counter;

    doubleCounterState;
  }

  void createEffect(ValueNotifier<Object?> notifier, void Function() fn) {
    $effectFnInfo ??= {};
    MacroEffectUtils.createEffect(notifier, fn, $effectFnInfo!, $untrackedFns);
  }

  void addEffect(ValueNotifier<Object?> dependency, void Function() fn) {
    $effectFnInfo ??= {};
    MacroEffectUtils.removeEffect(dependency, fn, $effectFnInfo);
    MacroEffectUtils.createEffect(dependency, fn, $effectFnInfo!, $untrackedFns);
  }

  void removeEffect(ValueNotifier<Object?> dependency, void Function() fn) {
    MacroEffectUtils.removeEffect(dependency, fn, $effectFnInfo);
  }

  void untracked(
    void Function() fn, {
    void Function()? effectFn,
    List<void Function()>? effectFns,
  }) async {
    if ($untrackedFns == const <void Function()>{}) {
      $untrackedFns = {};
    }
    MacroEffectUtils.untracked(
      fn,
      effectFn: effectFn,
      effectFns: effectFns,
      effectFnInfo: $effectFnInfo,
      untrackedFns: $untrackedFns,
    );
  }

  void dispose() {
    counterState.dispose();
    doubleCounterState.dispose();
  }
}

/// A mixin for [MyCounter]. Don't forget to call [initState] in the constructor.
mixin MyCounterModel {
  @protected
  @pragma('vm:prefer-inline')
  @pragma('dart2js:tryInline')
  MyCounter get $ => this as MyCounter;

  @protected
  EffectFnInfo? $effectFnInfo;
  Set<void Function()> $untrackedFns = const {};

  // -------------------- Environments --------------------
  late CalculatorService calculatorService = $.calculatorServiceEnv;
  late final ValueNotifier<CalculatorService> $calculatorService2Notifier = () {
    final notifier = $.calculatorService2Env;
    notifier.addListener($calculatorService2Changed);
    return notifier;
  }();
  late CalculatorService calculatorService2 = $calculatorService2Notifier.value;

  void $calculatorService2Changed() {
    final payload = {'calculatorService2': calculatorService2};
    calculatorService2 = $calculatorService2Notifier.value;
    $.calculatorService2EnvChanged(payload);
    $.multipleEnvChanged();
    $.myCounter2EnvChanged(payload);
  }

  late final ValueNotifier<CalculatorService> $myServiceNotifier = () {
    final notifier = $.myServiceEnv;
    notifier.addListener($myServiceChanged);
    return notifier;
  }();
  late CalculatorService myService = $myServiceNotifier.value;

  void $myServiceChanged() {
    myService = $myServiceNotifier.value;
    $.multipleEnvChanged();
  }

  // -------------------- States --------------------------
  final titleState = ValueNotifier<String>('');
  final counterState = ValueNotifier<int>(0);

  // -------------------- Computed ------------------------
  late final ValueNotifier<int> doubleCounterState = () {
    final state = ValueNotifier<int>($.doubleCounter);
    counterState.addListener($doubleCounterDepsChanged);
    return state;
  }();

  void $doubleCounterDepsChanged() {
    doubleCounterState.value = $.doubleCounter;
  }

  bool $initCalled = false;

  @mustCallSuper
  void initState() {
    if ($initCalled) return;
    $initCalled = true;

    final $ = this.$;
    calculatorService2;
    myService;

    titleState.value = $.title;
    counterState.value = $.counter;

    doubleCounterState;

    createEffect(counterState, $.logCounter);
    createEffect(counterState, $.logCounter2);
    createEffect(titleState, $.logCounter2);
  }

  void createEffect(ValueNotifier<Object?> notifier, void Function() fn) {
    $effectFnInfo ??= {};
    MacroEffectUtils.createEffect(notifier, fn, $effectFnInfo!, $untrackedFns);
  }

  void addEffect(ValueNotifier<Object?> dependency, void Function() fn) {
    $effectFnInfo ??= {};
    MacroEffectUtils.removeEffect(dependency, fn, $effectFnInfo);
    MacroEffectUtils.createEffect(dependency, fn, $effectFnInfo!, $untrackedFns);
  }

  void removeEffect(ValueNotifier<Object?> dependency, void Function() fn) {
    MacroEffectUtils.removeEffect(dependency, fn, $effectFnInfo);
  }

  void untracked(
    void Function() fn, {
    void Function()? effectFn,
    List<void Function()>? effectFns,
  }) async {
    if ($untrackedFns == const <void Function()>{}) {
      $untrackedFns = {};
    }
    MacroEffectUtils.untracked(
      fn,
      effectFn: effectFn,
      effectFns: effectFns,
      effectFnInfo: $effectFnInfo,
      untrackedFns: $untrackedFns,
    );
  }

  void dispose() {
    titleState.dispose();
    counterState.dispose();
    doubleCounterState.dispose();
    $calculatorService2Notifier.removeListener($calculatorService2Changed);
    $myServiceNotifier.removeListener($myServiceChanged);
  }
}
