// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of 'widget_state.dart';

abstract class BaseMyHomePageState extends State<MyHomePage> with BaseStateMixin<MyHomePage> {
  @protected
  @pragma('vm:prefer-inline')
  @pragma('dart2js:tryInline')
  MyHomePageState get $ => this as MyHomePageState;

  final titleState = ValueNotifier<String>('');
  final counterState = ValueNotifier<int>(0);
  late final ValueNotifier<int> doubleCounterState = () {
    final state = ValueNotifier<int>($.doubleCounter);
    counterState.addListener($doubleCounterDependsRebuild);
    return state;
  }();

  void $doubleCounterDependsRebuild() {
    doubleCounterState.value = $.doubleCounter;
  }

  final ValueNotifier<int> $fetchDataSource = ValueNotifier(0);
  late final Resource<int> fetchDataQuery = () {
    counterState.addListener($fetchDataSourceChanged);
    return Resource(
      $.fetchData,
      source: $fetchDataSource,
      useRefreshing: true,
      debounceDelay: null,
      trackPreviousState: true,
    );
  }();
  void $fetchDataSourceChanged() {
    $fetchDataSource.value++;
  }

  late final MyCounter myCounter = Provider.of(context, listen: false);
  late final MyCounter myCounterAnotherWay = Provider.of(context, listen: false);
  late MyCounter myCounter2;
  late MyCounter myCounter3 = $.myCounter3Env;
  late final ValueNotifier<MyCounter> $myCounter4Notifier = () {
    final notifier = $.myCounter4Env;
    notifier.addListener($myCounter4Changed);
    return notifier;
  }();
  late MyCounter myCounter4 = $myCounter4Notifier.value;

  void $myCounter4Changed() {
    final payload = {'myCounter4Env': myCounter4};
    myCounter4 = $myCounter4Notifier.value;
    $.myCounter4EnvChanged(payload);
    $.multipleEnvChanged();
    setState(() {});
  }

  @override
  void initState() {
    super.initState();
    //
  }

  void _initState() {
    final $ = this.$;

    titleState.value = $.title;
    counterState.value = $.counter;

    myCounter2 = Provider.of(context, listen: true);
    myCounter4;

    doubleCounterState;

    createEffect(counterState, $.logCounter);
    createEffect(counterState, $.logCounter2);
    createEffect(titleState, $.logCounter2);
  }

  @override
  @mustCallSuper
  void didChangeDependencies() {
    if (!didInitState) {
      _initState();
      didInitState = true;
      super.didChangeDependencies();
      return;
    }

    final payload = {
      'myCounter2Env': myCounter2,
    };

    myCounter2 = Provider.of(context, listen: true);
    $.multipleEnvChanged();
    $.myCounter2EnvChanged(payload);
    super.didChangeDependencies();
  }

  @override
  void didUpdateWidget(covariant MyHomePage old) {
    if (old.title != widget.title) {
      titleState.value = widget.title;
    }

    super.didUpdateWidget(old);
  }

  @override
  void dispose() {
    titleState.dispose();
    counterState.dispose();
    doubleCounterState.dispose();
    fetchDataQuery.dispose();
    $fetchDataSource.dispose();
    $myCounter4Notifier.removeListener($myCounter4Changed);
    super.dispose();
  }
}
