// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'widget_state.dart';

abstract class BaseMyHomePageState extends State<MyHomePage> with BaseStateMixin<MyHomePage> {
  @protected
  @pragma('vm:prefer-inline')
  @pragma('dart2js:tryInline')
  MyHomePageState get $ => this as MyHomePageState;

  // -------------------- Environments --------------------
  late final MyCounter myCounter = Provider.of(context, listen: false);
  late final MyCounter myCounterAnotherWay = Provider.of(context, listen: false);
  late MyCounter myCounter2;
  late MyCounter myCounter3 = $.myCounter3Env;
  late final ValueNotifier<MyCounter> $myCounter4Notifier = () {
    final notifier = $.myCounter4Env;
    notifier.addListener($myCounter4Changed);
    return notifier;
  }();
  late MyCounter myCounter4 = $myCounter4Notifier.value;

  void $myCounter4Changed() {
    final payload = {'myCounter4': myCounter4};
    myCounter4 = $myCounter4Notifier.value;
    $.myCounter4EnvChanged(payload);
    $.multipleEnvChanged();
    setState(() {});
  }

  // -------------------- States --------------------------
  final titleState = ValueNotifier<String>('');
  final counterState = ValueNotifier<int>(0);

  // -------------------- Computed ------------------------
  late final ValueNotifier<int> doubleCounterState = () {
    final state = ValueNotifier<int>($.doubleCounter);
    counterState.addListener($doubleCounterDepsChanged);
    return state;
  }();

  void $doubleCounterDepsChanged() {
    doubleCounterState.value = $.doubleCounter;
  }

  // -------------------- Queries --------------------
  final ValueNotifier<int> $fetchDataSource = ValueNotifier(0);
  late final Resource<int> fetchDataQuery = () {
    counterState.addListener($fetchDataSourceChanged);
    return Resource(
      $.fetchData,
      source: $fetchDataSource,
      useRefreshing: true,
      debounceDelay: null,
      trackPreviousState: false,
    );
  }();
  void $fetchDataSourceChanged() {
    $fetchDataSource.value++;
  }

  void _initState() {
    final $ = this.$;
    myCounter2 = Provider.of(context, listen: true);
    myCounter4;

    titleState.value = $.title;
    counterState.value = $.counter;

    doubleCounterState;

    createEffect(counterState, $.logCounter);
    createEffect(counterState, $.logCounter2);
    createEffect(titleState, $.logCounter2);
  }

  @override
  @mustCallSuper
  void didChangeDependencies() {
    if (!didInitState) {
      _initState();
      didInitState = true;
      super.didChangeDependencies();
      return;
    }
    final payload = {
      'myCounter2': myCounter2,
    };

    myCounter2 = Provider.of(context, listen: true);

    $.multipleEnvChanged();
    $.myCounter2EnvChanged(payload);

    super.didChangeDependencies();
  }

  @override
  void didUpdateWidget(covariant MyHomePage old) {
    if (old.title != widget.title) {
      titleState.value = widget.title;
    }

    super.didUpdateWidget(old);
  }

  @override
  void dispose() {
    fetchDataQuery.dispose();
    $fetchDataSource.dispose();
    titleState.dispose();
    counterState.dispose();
    doubleCounterState.dispose();
    $myCounter4Notifier.removeListener($myCounter4Changed);
    super.dispose();
  }
}
