name: widget_macro
description: A macro-powered simple state management solution for Flutter to eliminate boilerplate.
version: 1.1.1
repository: https://github.com/rebaz94/widget_macro
topics:
  - state-management
  - reactivity
  - dependency-injection

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  macro_kit: ^0.6.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  path:
  provider: